name: clang-format-check

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "clang-format-check:"
  clang-format-check:
    # The type of runner that the job will run on
    runs-on:
      - self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: false

      # Runs a set of commands using the runners shell
      - name: clang-format-check
        run: |

          # Remove the submodules
          git submodule deinit --force --all

          # Reformat all of the c files
          CFILES=$(find . -iname "*.c")
          for cFile in ${CFILES}
          do
            clang-format --verbose -style=file -n -Werror ${cFile}
          done
          
          # Reformat all of the header files
          HFILES=$(find . -iname "*.h" -not -name "*regs*")
          for hFile in ${HFILES}
          do
            clang-format --verbose -style=file -n -Werror ${hFile}
          done
