name: Build_Examples

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build_Examples"
  Build_Examples:
    # The type of runner that the job will run on
    runs-on:
      - ubuntu-latest

    steps:
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '11.2-2022.02' # <-- The compiler release to use

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          # Update the submodules below, doing so here will convert ssh to https
          submodules: false
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Build_Examples
        run: |
          # Install RISCV tools
          npm install --global xpm@latest
          
          TOOL_VER=10.2.0-1.2.1
          xpm install --global @xpack-dev-tools/riscv-none-embed-gcc@$TOOL_VER
          
          # Rest PATH
          PATH=$(getconf PATH)
          
          # Add riscv tools to path
          export PATH=$PATH:/home/runner/.local/xPacks/@xpack-dev-tools/riscv-none-embed-gcc/$TOOL_VER/.content/bin
          
          # Install ccache
          sudo apt install -y ccache

          # Update symlinks
          sudo /usr/sbin/update-ccache-symlinks

          # Prepend ccache into the PATH
          export PATH="/usr/lib/ccache:$PATH"
          
          # Setup the links
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-addr2line
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-ar
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-as
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-c
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-c++filt
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-cpp
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-elfedit
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-g
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gcc
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gcc-10.2.1
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gcc-ar
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gcc-nm
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gcc-ranlib
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gcov
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gcov-dump
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gcov-tool
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gdb-add-index
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gdb-add-index-py
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gdb-py
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-gprof
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-ld
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-ld.bfd
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-lto-dump
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-nm
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-objcopy
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-objdump
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-ranlib
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-readelf
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-size
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-strings
          sudo ln -s ../../bin/ccache /usr/local/bin/arm-none-eabi-strip
          sudo ln -s ../../bin/ccache /usr/local/bin/riscv-none-embed-gcc
          
          # Test the ccache paths
          echo $PATH
          ls -la $(which arm-none-eabi-gcc)
          ls -la $(which riscv-none-embed-gcc)
          
          exit 1

          # This environment variable is required for the SBTs.
          # It must be set to the absolute path inside the Github repo.
          export MAXIM_SBT_DIR=$(pwd)/Tools/SBT

          cd Examples
          # Rebuild all of the peripheral drivers and build all of the Hello_World examples
          # Exclude the MAX32572, currently in development
          # Exclude the MAX32570, examples are located in another repo
          SUBDIRS=$(find . -type d -not -path "./MAX3257*" -name "Hello_World")
          for dir in ${SUBDIRS}
          do
            echo
            echo "-----------------------------------------"
            echo ${dir}
            echo "-----------------------------------------"
            echo
            make -C ${dir} clean
            make -C ${dir} libclean
            make -C ${dir} -j8 > /dev/null
          done
          
          # Find all of the examples, 
          # Exclude the MAX32572, currently in development
          # Exclude the MAX32570, examples are located in another repo
          SUBDIRS=$(find . -mindepth 3 -not \( -path "./MAX3257*" -o -path "./MAX*/UCL*" \) -name "?akefile" -printf '%h\n')

          # Exclude some examples
          SUBDIRS=${SUBDIRS//"./MAX32672/Display/lvgl-8.0.2/tests"/}
          SUBDIRS=${SUBDIRS//"./MAX32572/MAX32572_Demo_FreeRTOS"/}
          SUBDIRS=${SUBDIRS//"./MAX32572/MAX32572_Demo_BareMetal"/}
          SUBDIRS=${SUBDIRS//"./MAX78000/CNN/mnist-streaming"/}

          for dir in ${SUBDIRS}
          do
            echo
            echo "-----------------------------------------"
            echo ${dir}
            echo "-----------------------------------------"
            echo

            make -C ${dir} clean
            make -C ${dir} -j8  > /dev/null
          done

          # Build MAX32690 WLP_V1 BLE examples
          SUBDIRS=$(find ./MAX32690 -type d -name "BLE*")
          echo SUBDIRS: ${SUBDIRS}

          for dir in ${SUBDIRS}
          do
            echo
            echo "---------------------------------------"
            echo ${dir}
            echo "---------------------------------------"
            echo
            make -C ${dir} clean
            make -C ${dir} libclean
            make -C ${dir} -j8 BOARD=WLP_V1  > /dev/null
          done
          
