# This is a basic workflow to help you get started with Actions

name: Build Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v2.3.3
        with:
          cache: pip
          
      - name: Install mkdocs
        run: pip install mkdocs

      - name: Doxygen (MAX32520)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max32520_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation

      - name: Doxygen (MAX32650)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max32650_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation
      
      - name: Doxygen (MAX32655)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max32655_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation

      - name: Doxygen (MAX32660)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max32660_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation

      - name: Doxygen (MAX32665)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max32665_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation

      - name: Doxygen (MAX32670)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max32670_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation

      - name: Doxygen (MAX32672)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max32672_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation

      - name: Doxygen (MAX32675)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max32675_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation

      - name: Doxygen (MAX32680)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max32680_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation

      - name: Doxygen (MAX78000)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max78000_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation

      - name: Doxygen (MAX78002)
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@c8ea8dfb83d5e54ca64b7bfcc9b10613a3ede71c
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: max78002_Doxyfile
          # Working directory
          working-directory: Libraries/PeriphDrivers/Documentation

      - name: Build User Guide
        run: |
          SOURCE=Libraries/PeriphDrivers/Documentation
          DEST=Documentation/$SOURCE

          mkdir -p $DEST/MAX32520 && cp -r $SOURCE/MAX32520 $DEST/MAX32520
          mkdir -p $DEST/MAX32650 && cp -r $SOURCE/MAX32650 $DEST/MAX32650
          mkdir -p $DEST/MAX32655 && cp -r $SOURCE/MAX32655 $DEST/MAX32655
          mkdir -p $DEST/MAX32660 && cp -r $SOURCE/MAX32660 $DEST/MAX32660
          mkdir -p $DEST/MAX32665 && cp -r $SOURCE/MAX32665 $DEST/MAX32665
          mkdir -p $DEST/MAX32670 && cp -r $SOURCE/MAX32670 $DEST/MAX32670
          mkdir -p $DEST/MAX32672 && cp -r $SOURCE/MAX32672 $DEST/MAX32672
          mkdir -p $DEST/MAX32675 && cp -r $SOURCE/MAX32675 $DEST/MAX32675
          mkdir -p $DEST/MAX32680 && cp -r $SOURCE/MAX32680 $DEST/MAX32680
          mkdir -p $DEST/MAX78000 && cp -r $SOURCE/MAX78000 $DEST/MAX78000
          mkdir -p $DEST/MAX78002 && cp -r $SOURCE/MAX78002 $DEST/MAX78002

          mkdocs build

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site # The folder the action should deploy.
