name: Build & Deploy Cordio Platform Docs (MAX32655)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Docs (MAX32655)
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: Libraries/Cordio/docs
          doxyfile-path: max32655_platform_doxyfile
          enable-latex: true

      - name: Build PDF
        run: |
          echo "Building PDF..."
          sudo apt-get install texlive-full
          sudo make -C Libraries/Cordio/docs/latex

          echo "Copying PDF to Cordio/platform/Documentation"
          sudo mv Libraries/Cordio/docs/latex/refman.pdf Libraries/Cordio/docs/latex/MAX32655.pdf
          sudo mkdir Libraries/Cordio/platform/Documentation && sudo cp -r Libraries/Cordio/docs/latex/MAX32655.pdf Libraries/Cordio/platform/Documentation/
          
          
      - name: Push Documentation Files
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: 'Libraries/Cordio/platform/Documentation/MAX32655.pdf'
          message: 'Update documentation.'
          new_branch: cordio-platform-docs
          push: true



        
