name: Build & Deploy Cordio Platform Docs (MAX32655)

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v3

  - name: Generate Docs (MAX32655)
    uses: mattnotmitt/doxygen-action@v1.9.5
    with:
      working-directory: Libraries/Cordio/Documentation
      doxyfile-path: max32655_platform_doxyfile
      enable-latex: true

  - name: Build PDF
    run: |
      echo "Building PDF..."
      SOURCE  = Libraries/Cordio/Documentation
      DEST = Libraries/Cordio/platform/Documentation
      make -C $SOURCE/latex
      
      echo "Copying PDF to Cordio/platform/Documentation"
      mv $SOURCE/latex/refman.pdf $DEST/MAX32655.pdf
      rm -r latex



        
