name: Build & Deploy Cordio Platform Docs (MAX32655)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Docs (MAX32655)
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: Libraries/Cordio/docs
          doxyfile-path: max32655_platform_doxyfile
          enable-latex: true

      - name: Build PDF
        run: |
          echo "Building PDF..."
          make -C Libraries/Cordio/docs/latex

          echo "Copying PDF to Cordio/platform/Documentation"
          mv Libraries/Cordio/docs/latex/refman.pdf Libraries/Cordio/platform/Documentation/MAX32655.pdf
          rm -r latex



        
