name: clang-format-run-pr

# Controls when the workflow will run
on:
  issue_comment:
      types: [created]

jobs:

  run-not-pr: 
    # Run on branchs, not forked PR branches
    if: |
      contains(github.event.comment.body, '/clang-format-run')

    runs-on:
      - self-hosted
      - software

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          
  
      # Runs a set of commands using the runners shell
      - name: clang-format-run
        run: |

          bash -ex .github/workflows/clang-format-run.sh

      - name: Push reformatted files
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: '*'
          message: 'clang-format bot reformatting.'
          push: true

  run-pr: 
    # Running on PR branches from fork
    if: |
      contains(github.event.comment.body, '/clang-format-run-pr')

    runs-on:
      - self-hosted
      - software

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          # Get on the appropriate branch
          repository: ${{ github.event.pull_request.head.repo.git_url }}
          ref: ${{ github.event.pull_request.head.ref }}

      # Runs a set of commands using the runners shell
      - name: clang-format-run
        run: |

          bash -ex .github/workflows/clang-format-run.sh

      - name: Push reformatted files
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: '*'
          message: 'clang-format bot reformatting.'
          push: true
