name: clang-format-commit

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkout-pr:
    runs-on:
      - self-hosted

    if: github.ref == "pull/*"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
  # checkout:
  #   runs-on:
  #     - self-hosted

  #   if: github.ref != "pull/*"
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: false

  clang-format-commit:
    runs-on:
      - self-hosted
    steps:

      # Runs a set of commands using the runners shell
      - name: clang-format-commit
        run: |

          echo "Hello World"

          # Remove the submodules
          git submodule deinit --force --all

          # Reformat all of the c files
          CFILES=$(find . -iname "*.c")
          for cFile in ${CFILES}
          do
            clang-format --verbose -style=file -i ${cFile}
          done
          
          # Reformat all of the header files
          HFILES=$(find . -iname "*.h" -not -name "*regs*")
          for hFile in ${HFILES}
          do
            clang-format --verbose -style=file -i ${hFile}
          done

          # Update the submodules, this will use ssh
          git submodule init
          git submodule sync
          git submodule update --init --recursive

      - name: Push reformatted files
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: '*'
          message: 'clang-format bot reformatting.'
          push: true
