name: clang-format-check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
      - self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: false
          repository: ${{ github.repository }}
          ref: ${{ github.github_ref }}

      # Runs a set of commands using the runners shell
      - name: clang-format-check
        run: |
          # Deinit all of the submodules
          set +e
          git submodule deinit --force --all
          set -e

          # Reformat all of the c files
          CFILES=$(find . -iname "*.c")
          for cFile in ${CFILES}
          do
            clang-format --verbose -style=file -i ${cFile}
          done
          
          # Reformat all of the header files
          HFILES=$(find . -iname "*.h" -not -name "*regs*")
          for hFile in ${HFILES}
          do
            clang-format --verbose -style=file -i ${hFile}
          done

      - name: Push reformatted files
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: '*'
          message: 'clang-format bot reformatting.'
          push: true
