name: clang-format-run

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  clang-format-run:

    # Do not run on Analog-Devices-MSDK/msdk:main branch
    if: |
      ${{ (github.ref != 'refs/heads/main' ||
      github.repository != 'Analog-Devices-MSDK/msdk') }}

    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0
          # Only works on branches, not PRs.

      # Runs a set of commands using the runners shell
      - name: clang-format-run
        run: |
          set -e
          # Don't return right away
          bash -ex .github/workflows/clang-format-run.sh
          RETVAL=$?
          set +e

          if [[ $RETVAL -eq 0 ]]
            exit 0
          fi

          # Files changed, not an error in this case
          if [[ $RETVAL -eq 1 ]]
            exit 0
          fi

          # Unexpected error
          exit $RETVAL

      - name: Push reformatted files
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: '*'
          message: 'clang-format bot reformatting.'
          push: true
