name: Deploy Docs

# Controls when the workflow will run
on:
  push:
    branches: [ "release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build the docs
  build:
    - uses: ./.github/workflows/build-docs.yml
  
  # Publish the docs
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # Deploy the built docs folder
